ARG BASE_IMAGE=skychip/erpnext-base:16.32.0

FROM ${BASE_IMAGE} AS backend

ARG APP_REPO=https://github.com/olan823/starcompany_integration.git
ARG APP_REF
ARG APP_COMMIT
ARG BASE_RELEASE=16.32.0
ARG GITHUB_PROXY_PREFIX=""

USER frappe

RUN if [ -n "${GITHUB_PROXY_PREFIX}" ]; then \
    git config --global url."${GITHUB_PROXY_PREFIX}https://github.com/".insteadOf "https://github.com/"; \
  fi && \
  grep -Eq "^erpnext v${BASE_RELEASE} [0-9a-f]{40}$" .erpnext-base-build && \
  bench get-app \
    --branch="${APP_REF}" \
    --skip-assets \
    starcompany_integration \
    "${APP_REPO}" && \
  test "$(git -C apps/starcompany_integration rev-parse HEAD)" = "${APP_COMMIT}" && \
  printf '%s\n' "${APP_REF} ${APP_COMMIT}" > .starcompany-build && \
  rm -rf apps/starcompany_integration/.git

RUN mkdir -p /home/frappe/frappe-bench/sites/assets/starcompany_integration && \
  cp -a \
    /home/frappe/frappe-bench/apps/starcompany_integration/starcompany_integration/public/. \
    /home/frappe/frappe-bench/sites/assets/starcompany_integration/ && \
  mkdir -p /home/frappe/frappe-bench/assets && \
  cp -a /home/frappe/frappe-bench/sites/assets/. /home/frappe/frappe-bench/assets/ && \
  rm -rf /home/frappe/frappe-bench/sites/assets

VOLUME [ \
  "/home/frappe/frappe-bench/sites", \
  "/home/frappe/frappe-bench/logs" \
]

USER root
COPY resources/core/main-entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 755 /usr/local/bin/entrypoint.sh

COPY resources/core/start.sh /usr/local/bin/start.sh
RUN chmod 755 /usr/local/bin/start.sh

USER frappe
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["start.sh"]