ARG FRAPPE_IMAGE_TAG=version-16
ARG FRAPPE_IMAGE_PREFIX=frappe

FROM ${FRAPPE_IMAGE_PREFIX}/build:${FRAPPE_IMAGE_TAG} AS builder

ARG FRAPPE_REF=v16.32.0
ARG FRAPPE_PATH=https://github.com/frappe/frappe
ARG FRAPPE_EXPECTED_COMMIT=""
ARG GITHUB_PROXY_PREFIX=""
ARG ERPNEXT_REF=v16.32.0
ARG ERPNEXT_EXPECTED_COMMIT=""

USER frappe

RUN --mount=type=secret,id=apps_json,target=/opt/frappe/apps.json,uid=1000,gid=1000 \
  if [ -n "${GITHUB_PROXY_PREFIX}" ]; then \
    git config --global url."${GITHUB_PROXY_PREFIX}https://github.com/".insteadOf "https://github.com/"; \
    git config --global url."${GITHUB_PROXY_PREFIX}https://github.com/frappe/gunicorn.git".insteadOf "https://github.com/frappe/gunicorn"; \
    git config --global url."${GITHUB_PROXY_PREFIX}https://github.com/frappe/pypika.git".insteadOf "https://github.com/frappe/pypika"; \
    git config --global url."${GITHUB_PROXY_PREFIX}https://github.com/frappe/air-datepicker.git".insteadOf "https://github.com/frappe/air-datepicker"; \
  fi && \
  export APP_INSTALL_ARGS="" && \
  if [ -f /opt/frappe/apps.json ] && [ -s /opt/frappe/apps.json ]; then \
    export APP_INSTALL_ARGS="--apps_path=/opt/frappe/apps.json"; \
  fi && \
  bench init ${APP_INSTALL_ARGS}\
    --frappe-branch=${FRAPPE_REF} \
    --frappe-path=${FRAPPE_PATH} \
    --no-procfile \
    --no-backups \
    --skip-redis-config-generation \
    --verbose \
    /home/frappe/frappe-bench && \
  cd /home/frappe/frappe-bench && \
  test "$(git -C apps/frappe rev-parse HEAD)" = "${FRAPPE_EXPECTED_COMMIT}" && \
  test "$(git -C apps/erpnext rev-parse HEAD)" = "${ERPNEXT_EXPECTED_COMMIT}" && \
  printf 'frappe %s %s\nerpnext %s %s\n' \
    "${FRAPPE_REF}" "${FRAPPE_EXPECTED_COMMIT}" \
    "${ERPNEXT_REF}" "${ERPNEXT_EXPECTED_COMMIT}" \
    > .erpnext-base-build && \
  echo "{}" > sites/common_site_config.json && \
  find apps -mindepth 1 -path "*/.git" | xargs rm -fr

FROM ${FRAPPE_IMAGE_PREFIX}/base:${FRAPPE_IMAGE_TAG} AS erpnext-base

USER frappe

COPY --from=builder --chown=frappe:frappe /home/frappe/frappe-bench /home/frappe/frappe-bench

WORKDIR /home/frappe/frappe-bench
